### ISSUE TITLE
AttributeError: 'module' object has no attribute 'full_load'

### ISSUE THREAD

**Issue by lioramilbaum** [openshift/elliott#17]
```
(venv) [lmilbaum@lmilbaum ~]$ elliott list
Traceback (most recent call last):
  File "/home/lmilbaum/.virtualenvs/venv/bin/elliott", line 722, in <module>
    main()
  File "/home/lmilbaum/.virtualenvs/venv/bin/elliott", line 711, in main
    cli(obj={})
  File "/home/lmilbaum/.virtualenvs/venv/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/lmilbaum/.virtualenvs/venv/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/lmilbaum/.virtualenvs/venv/lib/python2.7/site-packages/click/core.py", line 1134, in invoke
    Command.invoke(self, ctx)
  File "/home/lmilbaum/.virtualenvs/venv/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/lmilbaum/.virtualenvs/venv/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/lmilbaum/.virtualenvs/venv/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/lmilbaum/.virtualenvs/venv/bin/elliott", line 83, in cli
    cli_args=kwargs)
  File "/home/lmilbaum/.virtualenvs/venv/lib/python2.7/site-packages/dotconfig/__init__.py", line 74, in __init__
    data = yaml.full_load(f)
AttributeError: 'module' object has no attribute 'full_load'
```

**Comment by lioramilbaum** [comment]
pyyaml version 5.1 was required
