### ISSUE TITLE
SSLError: HTTPSConnectionPool(host='errata.devel.redhat.com', port=443): Max retries exceeded with url

### ISSUE THREAD

**Issue by shiywang** [openshift/elliott#34]
when I execute `find-bugs` this morning to the advisory I created.
```
➜  ~ elliott --group=openshift-3.9 find-bugs --auto  --add 41339
...
..
2019-04-17 11:16:21,621 INFO Using branch from group.yml: rhaos-3.9-rhel-7
Searching for bugs with target release(s): 3.9.0, 3.9.z
Found bugs: 1698136, 1693320, 1614291, 1653267, 1613280, 1686266, 1693036, 1686947, 1420235, 1678372, 1463717, 1550015, 1688642, 1508107, 1429788, 1645143
Adding 16 bugs to advisory 41339
Error: Erratum 41339: idsfixed: Bug #1614291 The bug is filed already in RHBA-2019:0758.
Bug #1653267 The bug is filed already in RHBA-2018:3748.

```
My first question it seems this bug has been attached to another advisory, so we should skip it ?
@smunilla 

if so, then I hit command like this, and error out:
```
➜  ~ elliott --group=openshift-3.9 find-bugs --id 1698136 --id 1693320  --id 1613280 --id 1686266 --id 1693036 --id 1686947 --id 1420235 --id 1678372 --id 1463717 --id 1550015 --id 1688642 --id 1508107 --id 1429788 --id  1645143 --add 41339
/home/shiywang/.config/elliott/settings.yaml
2019-04-17 11:28:40,572 INFO Data clone directory already exists, checking commit sha
2019-04-17 11:28:41,980 INFO https://github.com/openshift/ocp-build-data.git is already cloned and latest
/usr/lib/python2.7/site-packages/elliottlib/runtime.py:143: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  tmp_config = Model(yaml.load(group_yml.format(**replace_vars)))
2019-04-17 11:28:42,039 INFO Using branch from group.yml: rhaos-3.9-rhel-7
Adding 14 bugs to advisory 41339
Traceback (most recent call last):
  File "/usr/bin/elliott", line 854, in <module>
    main()
  File "/usr/bin/elliott", line 843, in main
    cli(obj={})
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/bin/elliott", line 425, in find_bugs
    advs.commit()
  File "/usr/lib/python2.7/site-packages/errata_tool/erratum.py", line 946, in commit
    self._write()
  File "/usr/lib/python2.7/site-packages/errata_tool/erratum.py", line 885, in _write
    r = self._put(url, data=pdata)
  File "/usr/lib/python2.7/site-packages/errata_tool/connector.py", line 189, in _put
    verify=self.ssl_verify)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 131, in put
    return request('put', url, data=data, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='errata.devel.redhat.com', port=443): Max retries exceeded with url: /api/v1/erratum/41339 (Caused by SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')",),))
```

I think this is more like a issue of https://github.com/red-hat-storage/errata-tool instead of elliot.
or maybe errata is really an old antique can't even handle ~10 connections ?
maybe we should add an limit on our `--id` parameters, like if more than 10 then please do this spereately ?

BTW  if we support adding multiple bugs maybe sth like `--add 1234, 3456, 7890` is better than `--id 1234 --id 3456 --id 7890` ?

**Comment by smunilla** [comment]
Correct on all counts! 

`requests.exceptions.SSLError: HTTPSConnectionPool(host='errata.devel.redhat.com', port=443): Max retries exceeded with url: /api/v1/erratum/41339 (Caused by SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')",),))` definitely means either 1) errata tool is having issues or 2) you're just having trouble getting to it (as happens to me when I forget to get on VPN first).

Yes, that format would be *so much better*. I just haven't had time to implement it. If you have the time to do so, that would be excellent. I know that doozer already does similar for image lists, so that would be a good place to start.

**Comment by shiywang** [comment]
sure, I can take a look and submit a pr on that
