### ISSUE TITLE
xmlrpclib.Fault: <Fault -32601: "The requested method 'Bug.get_bugs' was not found.">

### ISSUE THREAD

**Issue by shiywang** [openshift/elliott#40]
```
[jenkins@buildvm elliott]$ elliott --group=openshift-4.1 repair-bugs --from MODIFIED --to ON_QA --auto -a 38252
2019-04-29 23:01:06,154 INFO Cloning config data from git@github.com:openshift/ocp-build-data.git
2019-04-29 23:01:07,552 INFO Using branch from group.yml: rhaos-4.1-rhel-7
Fetching Erratum(errata_id=38252)
Getting bugs for advisory
Fetching data for 819 bugs: Hold on a moment, we have to grab each one
[***************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************]
[****************Traceback (most recent call last):
  File "/bin/elliott", line 974, in <module>
    main()
  File "/bin/elliott", line 963, in main
    cli(obj={})
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/bin/elliott", line 891, in repair_bugs
    raw_bug_list)
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 250, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 554, in get
    raise self._value
xmlrpclib.Fault: <Fault -32601: "The requested method 'Bug.get_bugs' was not found.">
```

**Comment by shiywang** [comment]
this might due to some dependencies problem of site-packages when I try to run on buildvm, but on my local laptop, it seems has some problem with 

```
➜  elliott git:(master)  ./elliott --group=openshift-4.1 repair-bugs --from MODIFIED --to ON_QA --auto -a 38252
/home/shiywang/.config/elliott/settings.yaml
2019-04-30 09:44:19,298 INFO Data clone directory already exists, checking commit sha
2019-04-30 09:44:20,671 INFO https://github.com/openshift/ocp-build-data.git is already cloned and latest
2019-04-30 09:44:20,831 INFO Using branch from group.yml: rhaos-4.1-rhel-7
Traceback (most recent call last):
  File "./elliott", line 890, in <module>
    main()
  File "./elliott", line 879, in main
    cli(obj={})
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "./elliott", line 816, in repair_bugs
    attached_bugs = [bzapi.getbug(i) for i in e.errata_bugs]
  File "/usr/lib/python2.7/site-packages/bugzilla/base.py", line 1072, in getbug
    extra_fields=extra_fields)
  File "/usr/lib/python2.7/site-packages/bugzilla/base.py", line 1062, in _getbug
    return self._getbugs([objid], permissive=False, **kwargs)[0]
  File "/usr/lib/python2.7/site-packages/bugzilla/base.py", line 1030, in _getbugs
    r = self._proxy.Bug.get(getbugdata)
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/site-packages/bugzilla/transport.py", line 104, in _ServerProxy__request
    self)._ServerProxy__request(methodname, params)
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1602, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/site-packages/bugzilla/transport.py", line 201, in request
    return self._request_helper(url, request_body)
  File "/usr/lib/python2.7/site-packages/bugzilla/transport.py", line 164, in _request_helper
    url, data=request_body, **self.request_defaults)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 581, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 686, in send
    r.content
  File "/usr/lib/python2.7/site-packages/requests/models.py", line 828, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
  File "/usr/lib/python2.7/site-packages/requests/models.py", line 753, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(0 bytes read, 2 more expected)', IncompleteRead(0 bytes read, 2 more expected))
```

**Comment by sosiouxme** [comment]
@shiywang this sounds like it was something local to your install... this has gotten stale, feel free to reopen if you still want a reminder though.
